/* 
  Practica 2 - Jenkinsfile dummy (PUNTO DE PARTIDA)

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/
 
pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Test') {
      /*
        `agent` dentro de un stage permite que SOLO ese stage se ejecute en un contexto concreto.
        En este caso, usamos Docker como capa de virtualizacion: los comandos se ejecutan dentro
        de un contenedor temporal.
      */
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
        sh 'mvn -version'
        sh 'apt-get update'
        sh 'apt-get install -y make'
        sh 'make lint' // La imagen utilizada no tiene make.
        //Podemos añadir make a la imagen (imagen algo más pesada), ejecutar directamente o crear una imagen
        //mvn -q -DskipTests=true test. Añadimos make para aprovechar el Makefile ya hecho
        //Los make son parte de un archivo llamado Makefile que permite definir instrucciones
        //y acortar algo que puede ser más largo, por ejemplo lint = mvn -q -DskipTests=true test
        sh 'make test'
      }
    }
    /**
    *Stage de build.
    */
    stage("Build"){
      steps{
        sh 'docker version'
        //Ahora vamos a construir imagen docker a partir de Dockerfile 
        sh 'docker build -t java-app:1.0 -f devops/Dockerfile .'
      }
    }
  }
}
