name: CI/CD Java

on:
  push:
  pull_request:
    branches: [develop, master]
  workflow_dispatch:
    inputs:
      RUN_CD:
        description: "Run CD stage"
        required: false
        type: boolean
        default: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Info
        run: |
          echo "branch=${GITHUB_REF_NAME}"
          echo "sha=${GITHUB_SHA}"

  cd:
    needs: ci
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.RUN_CD == true || github.ref_name == 'develop' || github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
